version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    tty: true
    ports:
      - "80:3000"
    volumes:
      - ./web:/web
    command: "yarn run dev"
    stdin_open: true
    tty: true
    restart: always
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "3000:8080"
    tty: true
    stdin_open: true
    tty: true
    restart: always
