SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+9:00";

CREATE DATABASE IF NOT EXISTS `harmful_animal` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS `harmful_animal_test` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
COMMIT;
